# Source Registry
# Master bibliography of all sources analyzed in this project
# Format: BibTeX-compatible YAML
# See AGENTS.md for field definitions

sources:

  # Example entry (commented out)
  # epoch-2024-training-costs:
  #   type: "REPORT"
  #   title: "How Much Does It Cost to Train Frontier AI Models?"
  #   author: ["Epoch AI"]
  #   year: 2024
  #   url: "https://epoch.ai/blog/how-much-does-it-cost-to-train-frontier-ai-models"
  #   accessed: "2026-01-18"
  #   reliability: 0.8
  #   bias_notes: "Pro-AI-progress framing but methodologically careful"
  #   claims_extracted: []
  #   analysis_file: ""
  #   topics: ["compute", "costs", "frontier-models"]
  #   domains: ["TECH", "RESOURCE"]

  # Conversational analyses
  gpt-2026-01-18-hottakes:
    type: "CONVO"
    title: "Post-Singularity Economics Hot Takes Analysis"
    author: ["lhl", "GPT-5.2-Pro"]
    year: 2026
    url: "https://chatgpt.com/c/696c71e2-ebe8-8322-90ee-2bd0e35cb7b1"
    accessed: "2026-01-18"
    reliability: 0.6  # Conversational, needs verification
    bias_notes: "Exploratory analysis session, claims need primary source verification"
    claims_extracted:
      - "TECH-2026-004"
      - "DIST-2026-001"
      - "DIST-2026-002"
      - "DIST-2026-005"
      - "DIST-2026-006"
      - "GOV-2026-004"
      - "GOV-2026-005"
      - "GOV-2026-006"
      - "GOV-2026-007"
    analysis_file: "analysis/syntheses/neofeudalism-discourse-synthesis.md"
    topics: ["neofeudalism", "post-labor", "automation", "underclass", "multipolarity"]
    domains: ["LABOR", "DIST", "GOV", "TECH", "TRANS"]

  gpt-2026-01-18-fiction-hottakes:
    type: "CONVO"
    title: "Fiction Recommendations then Hot Takes Analysis"
    author: ["lhl", "GPT-5.2-Pro"]
    year: 2026
    url: ""
    accessed: "2026-01-18"
    reliability: 0.6
    bias_notes: "Exploratory analysis session"
    claims_extracted:
      - "TECH-2026-004"
      - "DIST-2026-001"
      - "DIST-2026-002"
      - "DIST-2026-005"
      - "DIST-2026-006"
      - "GOV-2026-006"
    analysis_file: "analysis/syntheses/neofeudalism-discourse-synthesis.md"
    topics: ["neofeudalism", "post-labor", "fiction", "alternatives"]
    domains: ["LABOR", "DIST", "SOCIAL"]

  # Primary sources referenced in conversations
  hotz-2026-three-minutes:
    type: "BLOG"
    title: "You have three minutes to escape the perpetual underclass"
    author: ["George Hotz"]
    year: 2026
    url: "https://geohot.github.io/blog/jekyll/update/2026/01/17/three-minutes.html"
    accessed: "2026-01-18"
    reliability: 0.5
    bias_notes: "Individual opinion, provocative framing"
    claims_extracted:
      - "GOV-2026-001"
    analysis_file: "analysis/syntheses/neofeudalism-discourse-synthesis.md"
    topics: ["neofeudalism", "tech-work", "participation"]
    domains: ["LABOR", "DIST", "SOCIAL"]

  hotz-2026-how-stop:
    type: "BLOG"
    title: "How do I stop?"
    author: ["George Hotz"]
    year: 2026
    url: "https://geohot.github.io/blog/jekyll/update/2026/01/18/how-do-i-stop.html"
    accessed: "2026-01-18"
    reliability: 0.5
    bias_notes: "Follow-up to three-minutes, more operational"
    claims_extracted: []  # Claims extracted via synthesis, not direct analysis
    analysis_file: "analysis/syntheses/neofeudalism-discourse-synthesis.md"
    topics: ["open-source", "ownership", "alternatives"]
    domains: ["TECH", "DIST"]

  teortaxes-2026-thread:
    type: "SOCIAL"
    title: "Post-labor permanent underclass Twitter thread"
    author: ["@teortaxesTex"]
    year: 2026
    url: ""  # Twitter thread, embedded in RESEARCH files
    accessed: "2026-01-18"
    reliability: 0.4
    bias_notes: "Twitter thread, provocative framing, some claims unfalsifiable"
    claims_extracted:
      - "TECH-2026-003"
      - "LABOR-2026-002"
      - "LABOR-2026-003"
      - "VALUE-2026-002"
      - "DIST-2026-003"
      - "GOV-2026-003"
    analysis_file: "analysis/syntheses/neofeudalism-discourse-synthesis.md"
    topics: ["post-labor", "automation", "permanent-underclass", "timeline"]
    domains: ["LABOR", "DIST", "GOV", "TECH"]

  teortaxes-2026-greenland-endgame:
    type: "SOCIAL"
    title: "Greenland/resource extraction + 'light cone' endgame post"
    author: ["@teortaxesTex"]
    year: 2026
    url: "https://x.com/teortaxesTex/status/2012127205728440495"
    accessed: "2026-01-18"
    reliability: 0.3
    bias_notes: "Highly narrativized geopolitical speculation; many claims are rhetorical/unfalsifiable; contains slurs/profanity"
    claims_extracted:
      - "RESOURCE-2026-003"
      - "GOV-2026-012"
      - "GOV-2026-013"
      - "GOV-2026-014"
      - "GOV-2026-015"
      - "TRANS-2026-001"
      - "TRANS-2026-002"
    analysis_file: "analysis/sources/teortaxes-2026-greenland-endgame.md"
    topics: ["geopolitics", "resources", "greenland", "nato", "automation", "spacefaring", "longtermism"]
    domains: ["GOV", "RESOURCE", "TRANS"]
    status: "analyzed"

  xenoimpulse-2026-thread:
    type: "SOCIAL"
    title: "Genocide > UBI nihilistic thread"
    author: ["@Xenoimpulse"]
    year: 2026
    url: "https://threadreaderapp.com/thread/2012723101835145461.html"
    accessed: "2026-01-18"
    reliability: 0.3
    bias_notes: "Extreme nihilistic framing, multiple weak premises"
    claims_extracted:
      - "GOV-2026-002"
      - "GOV-2026-008"
      - "GOV-2026-009"
      - "GOV-2026-010"
      - "GOV-2026-011"
    analysis_file: "analysis/syntheses/neofeudalism-discourse-synthesis.md"
    topics: ["genocide", "ubi", "coercion", "elite-coordination"]
    domains: ["GOV", "DIST"]

  # External sources cited in analysis (not directly analyzed, referenced for evidence)
  epoch-2024-training-costs:
    type: "REPORT"
    title: "How Much Does It Cost to Train Frontier AI Models?"
    author: ["Epoch AI"]
    year: 2024
    url: "https://epoch.ai/blog/how-much-does-it-cost-to-train-frontier-ai-models"
    accessed: "2026-01-18"
    reliability: 0.8
    bias_notes: "Pro-AI-progress framing but methodologically careful"
    claims_extracted:
      - "TECH-2026-001"
      - "TECH-2026-002"
    analysis_file: ""  # Cited, not directly analyzed
    topics: ["compute", "costs", "frontier-models"]
    domains: ["TECH", "RESOURCE"]

  iea-2024-energy-ai:
    type: "REPORT"
    title: "Energy and AI: Energy Supply for AI"
    author: ["IEA"]
    year: 2024
    url: "https://www.iea.org/reports/energy-and-ai/energy-supply-for-ai"
    accessed: "2026-01-18"
    reliability: 0.85
    bias_notes: "Institutional source, generally credible on energy data"
    claims_extracted:
      - "RESOURCE-2026-001"
    analysis_file: ""
    topics: ["energy", "datacenters", "electricity"]
    domains: ["RESOURCE", "TECH"]

  # Additional cited sources (stub entries for integrity)
  deepseek-r1:
    type: "PAPER"
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning"
    author: ["DeepSeek AI"]
    year: 2025
    url: "https://arxiv.org/abs/2501.12948"
    accessed: "2026-01-18"
    reliability: 0.7
    bias_notes: "Industry research paper"
    claims_extracted:
      - "TECH-2026-004"
    analysis_file: ""
    topics: ["reasoning", "llm", "open-models"]
    domains: ["TECH"]
    status: "cataloged"

  chm-alexnet:
    type: "ARTICLE"
    title: "CHM Releases AlexNet Source Code"
    author: ["Computer History Museum"]
    year: 2024
    url: "https://computerhistory.org/blog/chm-releases-alexnet-source-code/"
    accessed: "2026-01-18"
    reliability: 0.9
    bias_notes: "Historical documentation"
    claims_extracted:
      - "TECH-2026-003"
    analysis_file: ""
    topics: ["alexnet", "deep-learning", "history"]
    domains: ["TECH"]
    status: "cataloged"

  reuters-rio-tinto-amazon:
    type: "ARTICLE"
    title: "Rio Tinto to supply copper to Amazon for AI data centers"
    author: ["Reuters"]
    year: 2026
    url: "https://www.reuters.com/business/rio-tinto-supply-copper-amazon-ai-data-centers-2026-01-15/"
    accessed: "2026-01-18"
    reliability: 0.85
    bias_notes: "News wire, factual reporting"
    claims_extracted:
      - "RESOURCE-2026-002"
    analysis_file: ""
    topics: ["copper", "supply-chain", "vertical-integration"]
    domains: ["RESOURCE", "TECH"]
    status: "cataloged"

  japan-ai-guidelines-2025:
    type: "REPORT"
    title: "Guideline for Japanese Governments' Procurements and Utilizations of Generative AI"
    author: ["Digital Agency of Japan"]
    year: 2025
    url: "https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/e2a06143-ed29-4f1d-9c31-0f06fca67afc/6e45a64f/20250527_resources_standard_guidelines_guideline_04.pdf"
    accessed: "2026-01-18"
    reliability: 0.8
    bias_notes: "Government guidance document"
    claims_extracted:
      - "GOV-2026-007"
    analysis_file: ""
    topics: ["japan", "ai-governance", "regulation"]
    domains: ["GOV", "TECH"]
    status: "cataloged"

  eu-ai-act:
    type: "REPORT"
    title: "AI Act - Regulatory Framework for AI"
    author: ["European Commission"]
    year: 2024
    url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai"
    accessed: "2026-01-18"
    reliability: 0.85
    bias_notes: "Official EU regulatory framework"
    claims_extracted:
      - "GOV-2026-007"
    analysis_file: ""
    topics: ["eu", "ai-governance", "regulation"]
    domains: ["GOV", "TECH"]
    status: "cataloged"

  acemoglu-restrepo-2019-tasks:
    type: "PAPER"
    title: "Automation and New Tasks: How Technology Displaces and Reinstates Labor"
    author: ["Daron Acemoglu", "Pascual Restrepo"]
    year: 2019
    url: "https://www.aeaweb.org/articles?id=10.1257/jep.33.2.3"
    accessed: "2026-01-18"
    reliability: 0.85
    bias_notes: "Peer-reviewed academic economics"
    claims_extracted: []  # Referenced as counterargument, not directly extracted
    analysis_file: ""
    topics: ["automation", "labor", "tasks", "economics"]
    domains: ["LABOR", "TECH"]
    status: "cataloged"

  situational-awareness:
    type: "REPORT"
    title: "SITUATIONAL AWARENESS: The Decade Ahead"
    author: ["Leopold Aschenbrenner"]
    year: 2024
    url: "https://situational-awareness.ai/"
    accessed: "2026-01-18"
    reliability: 0.6
    bias_notes: "Forward-looking essay series; pro-AI-progress framing; not peer reviewed"
    claims_extracted: []  # Cited in synthesis; not directly extracted
    analysis_file: ""
    topics: ["ai-forecasting", "compute", "agi", "national-security"]
    domains: ["TECH", "RESOURCE", "GOV", "TRANS"]
    status: "cataloged"

  ai-2027:
    type: "REPORT"
    title: "AI 2027"
    author: ["Daniel Kokotajlo", "Scott Alexander", "Thomas Larsen", "Eli Lifland", "Romeo Dean"]
    year: 2025
    url: "https://ai-2027.com/"
    accessed: "2026-01-18"
    reliability: 0.6
    bias_notes: "Scenario forecast; speculative; useful for discriminating indicators"
    claims_extracted: []  # Cited in synthesis; not directly extracted
    analysis_file: ""
    topics: ["ai-forecasting", "timelines", "agents", "alignment"]
    domains: ["TECH", "TRANS", "GOV"]
    status: "cataloged"

  hooker-hardware-lottery:
    type: "PAPER"
    title: "The Hardware Lottery"
    author: ["Sara Hooker"]
    year: 2020
    url: "https://hardwarelottery.github.io/"
    accessed: "2026-01-18"
    reliability: 0.75
    bias_notes: "Perspective paper on how hardware availability shapes ML research; arXiv:2009.06489"
    claims_extracted: []  # Cited in synthesis; not directly extracted
    analysis_file: ""
    topics: ["hardware", "compute", "ml", "research"]
    domains: ["TECH", "RESOURCE", "DIST"]
    status: "cataloged"

  varoufakis-technofeudalism:
    type: "BOOK"
    title: "Technofeudalism: What Killed Capitalism"
    author: ["Yanis Varoufakis"]
    year: 2024
    url: "https://www.penguinrandomhouse.com/books/751443/technofeudalism-by-yanis-varoufakis/"
    accessed: "2026-01-18"
    reliability: 0.65
    bias_notes: "Heterodox political economy; provocative framing; useful as theory reference"
    claims_extracted: []  # Cited in synthesis; not directly extracted
    analysis_file: ""
    topics: ["technofeudalism", "platforms", "capitalism", "political-economy"]
    domains: ["DIST", "VALUE", "GOV"]
    status: "cataloged"

  butler-1863-darwin-machines:
    type: "ARTICLE"
    title: "Darwin among the Machines"
    author: ["Samuel Butler"]
    year: 1863
    url: "https://en.wikisource.org/wiki/Darwin_among_the_Machines"
    accessed: "2026-01-18"
    reliability: 0.9
    bias_notes: "Primary historical text; wikisource transcription"
    claims_extracted: []  # Cited in synthesis; not directly extracted
    analysis_file: ""
    topics: ["automation", "machines", "history"]
    domains: ["TECH", "SOCIAL"]
    status: "cataloged"

  # Background knowledge (stub entries for standard references)
  standard-economics:
    type: "KNOWLEDGE"
    title: "Standard economic theory (factor shares, labor economics)"
    author: ["Background Knowledge"]
    year: 0
    url: ""
    accessed: "2026-01-18"
    reliability: 0.8
    bias_notes: "Represents mainstream economic consensus on labor/capital dynamics"
    claims_extracted:
      - "LABOR-2026-001"
    analysis_file: ""
    topics: ["economics", "labor", "capital"]
    domains: ["LABOR", "VALUE"]
    status: "cataloged"

  macro-identity:
    type: "KNOWLEDGE"
    title: "Macroeconomic accounting identities (demand = income)"
    author: ["Background Knowledge"]
    year: 0
    url: ""
    accessed: "2026-01-18"
    reliability: 0.9
    bias_notes: "Definitional/accounting identity, not contested"
    claims_extracted:
      - "VALUE-2026-001"
    analysis_file: ""
    topics: ["macroeconomics", "demand", "income"]
    domains: ["VALUE"]
    status: "cataloged"

  historical-pattern:
    type: "KNOWLEDGE"
    title: "Historical pattern of technology diffusion and commoditization"
    author: ["Background Knowledge"]
    year: 0
    url: ""
    accessed: "2026-01-18"
    reliability: 0.7
    bias_notes: "General historical pattern, specific instances vary"
    claims_extracted:
      - "DIST-2026-004"
    analysis_file: ""
    topics: ["technology", "diffusion", "history"]
    domains: ["TECH", "DIST"]
    status: "cataloged"

  # Greenland Endgame analysis sources
  teortaxes-2026-greenland-endgame:
    type: "SOCIAL"
    title: "Greenland/resource extraction + 'light cone' endgame post"
    author: ["@teortaxesTex"]
    year: 2026
    url: "https://x.com/teortaxesTex/status/2012127205728440495"
    accessed: "2026-01-19"
    reliability: 0.3
    bias_notes: "Provocative framing; 'heavily narrativized'; mixes plausible geopolitics with speculative longtermist motives"
    claims_extracted:
      - "TRANS-2026-001"
      - "TRANS-2026-002"
      - "GOV-2026-012"
      - "GOV-2026-013"
      - "GOV-2026-014"
      - "GOV-2026-015"
      - "RESOURCE-2026-003"
    analysis_file: "analysis/sources/teortaxes-2026-greenland-endgame.md"
    topics: ["greenland", "resource-extraction", "longtermism", "light-cone", "geopolitics", "europe"]
    domains: ["GOV", "TRANS", "RESOURCE"]
    status: "analyzed"

  gpt-2026-01-19-greenland-endgame:
    type: "CONVO"
    title: "Raw critical analysis of Greenland Endgame thread (no framework)"
    author: ["lhl", "GPT-5.2-Pro"]
    year: 2026
    url: "https://chatgpt.com/c/696d1df5-91a0-8324-9137-9644a9f2e779"
    accessed: "2026-01-19"
    reliability: 0.7
    bias_notes: "Thorough fact-checking; used as baseline for framework comparison"
    claims_extracted: []  # Raw analysis, claims not extracted to registry
    analysis_file: ""
    topics: ["greenland", "critical-analysis", "fact-checking", "framework-comparison"]
    domains: ["META"]
    status: "cataloged"

  claude-2026-01-19-framework-efficacy:
    type: "CONVO"
    title: "Meta-Analysis: Framework Efficacy Test (Greenland Endgame)"
    author: ["lhl", "Claude Opus 4.5"]
    year: 2026
    url: ""
    accessed: "2026-01-19"
    reliability: 0.7
    bias_notes: "Reflexive analysis of our own framework; potential confirmation bias mitigated by explicit gap identification"
    claims_extracted:
      - "META-2026-001"
      - "META-2026-002"
      - "META-2026-003"
      - "META-2026-004"
      - "META-2026-005"
    analysis_file: "analysis/meta/framework-efficacy-greenland-test.md"
    topics: ["meta-analysis", "framework-evaluation", "methodology", "workflow"]
    domains: ["META"]
    status: "analyzed"

  gpt-2026-01-19-framework-comparison:
    type: "CONVO"
    title: "ChatGPT's Self-Comparison: Raw vs Framework Analysis"
    author: ["lhl", "GPT-5.2-Pro"]
    year: 2026
    url: "https://chatgpt.com/c/696d1df5-91a0-8324-9137-9644a9f2e779"
    accessed: "2026-01-19"
    reliability: 0.75
    bias_notes: "ChatGPT comparing its own raw analysis to framework-guided analysis; provides external perspective on framework gaps"
    claims_extracted:
      - "META-2026-005"  # Updated with additional source
      - "META-2026-006"
      - "META-2026-007"
      - "META-2026-008"
    analysis_file: "analysis/meta/framework-efficacy-greenland-test.md"
    topics: ["meta-analysis", "framework-evaluation", "methodology", "self-comparison"]
    domains: ["META"]
    status: "analyzed"

# Statistics
# Total sources: 27
# By type: CONVO: 5, BLOG: 2, SOCIAL: 4, REPORT: 6, PAPER: 3, ARTICLE: 3, BOOK: 1, KNOWLEDGE: 3
# Last updated: 2026-01-19
